import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const sculpture=new URL('./assets/research-sculpture.png',import.meta.url).href;
const patientIcon=new URL('./assets/PatientConsent.svg',import.meta.url).href;
const privacyIcon=new URL('./assets/PrivacyEvidence.svg',import.meta.url).href;
const researchIcon=new URL('./assets/ResearchOverview.svg',import.meta.url).href;
const brandIcon=new URL('./assets/icon.svg',import.meta.url).href;

type Metrics = {accuracy:number; auroc:number|null; f1:number; sensitivity:number|null; specificity:number|null; test_count:number; threshold?:number};
type Hospital = {id:string; records:number; eligible:number; status:string; distribution:Record<string,number>|null};
type Patient = {patient_id:string; hospital:string; status:string; project:string; purpose:string; policy:string};
type Privacy = {epsilon:number; delta:number; noise_multiplier:number; clipping:number; sample_rate:number; history:number[][]};
type Round = {round:number; snapshot_at:string; metrics:Metrics|null; epsilon_max:number|null; hospitals:Record<string,{count:number; status:string; eligible_ids:string[]; privacy?:Privacy|null}>};
type Attack = {status:string; reason?:string; auroc?:number; balanced_accuracy?:number; tpr?:number; fpr?:number; counts?:Record<string,number>; scope?:string; limitation?:string};
type Run = {id:string; status:string; config:{noise:number; rounds:number; epochs:number; delta:number; seed:number; batch_size:number; learning_rate:number; clipping:number}; rounds:Round[]; baselines:Record<string,{metrics?:Metrics; status?:string}>; error:string|null; privacy_scope:string; started_at:string; evaluation?:string; attack?:Attack};
type Receipt = {record:Patient; eligible_now:boolean; history:{id:number; action:string; at:string}[]; rounds:{run_id:string; round:number; snapshot_at:string; eligible:boolean; participation:string; privacy:Privacy|null}[]; withdrawal_explanation:string; raw_data:string};
type Health = {busy:boolean; initialized:boolean};

async function api<T>(path:string, body?:unknown):Promise<T> {
  const response = await fetch(`/api${path}`, {...(body === undefined ? {} : {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(path==='/initialize'?120000:15000)});
  if (!response.ok) {
    const error = await response.json().catch(()=>({}));
    throw new Error(typeof error.detail === 'string' ? error.detail : `Request failed (${response.status}). Check your inputs and try again.`);
  }
  return response.json();
}
const value = (v:number|null|undefined) => v == null ? 'Not measured' : v.toFixed(3);
const percent = (v:number|null|undefined) => v == null ? 'Not measured' : `${(v*100).toFixed(1)}%`;
const date = (s:string) => new Date(s).toLocaleString();
const runLabel = (r:Run) => `${r.config.noise?`DP · noise ${r.config.noise}`:'Non-DP'} · ${r.config.rounds} rounds · ${r.id.slice(0,8)} · ${r.status}`;
function MetricTable({rows}:{rows:{name:string; metrics:Metrics}[]}) {
  return <div className="table-scroll" tabIndex={0} aria-label="Model metrics, scroll horizontally if needed"><table><caption>Same official test split · thresholds selected on validation for calibrated runs</caption><thead><tr><th>Model</th><th>AUROC</th><th>Accuracy</th><th>Recall</th><th>Specificity</th><th>F1</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><th>{r.name}</th><td>{value(r.metrics.auroc)}</td><td>{percent(r.metrics.accuracy)}</td><td>{percent(r.metrics.sensitivity)}</td><td>{percent(r.metrics.specificity)}</td><td>{value(r.metrics.f1)}</td></tr>)}</tbody></table></div>;
}
function App() {
  const [view,setView]=useState('research');
  const [metric,setMetric]=useState<'auroc'|'accuracy'|'f1'>('auroc');
  const [hospitals,setHospitals]=useState<Hospital[]>([]),[runs,setRuns]=useState<Run[]>([]),[health,setHealth]=useState<Health>({busy:false,initialized:false});
  const [selected,setSelected]=useState(''),[hospital,setHospital]=useState('A'),[patients,setPatients]=useState<Patient[]>([]),[patient,setPatient]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null);
  const [error,setError]=useState(''),[connectionError,setConnectionError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[loaded,setLoaded]=useState(false);
  const [noise,setNoise]=useState(0),[rounds,setRounds]=useState(3),[updated,setUpdated]=useState('');
  async function refresh() {
    const [h,r,s]=await Promise.all([api<Hospital[]>('/hospitals'),api<Run[]>('/experiments'),api<Health>('/health')]);
    setHospitals(h);setRuns(r);setHealth(s);setLoaded(true);setUpdated(new Date().toLocaleTimeString());setConnectionError('');
  }
  useEffect(()=>{
    let alive=true;let timer:number;
    const poll=async()=>{try{await refresh();}catch(e){if(alive)setConnectionError(`Connection lost. Results may be stale. ${(e as Error).message}`);}finally{if(alive)timer=window.setTimeout(poll,3000);}};
    void poll();return()=>{alive=false;clearTimeout(timer);};
  },[]);
  useEffect(()=>{
    let alive=true;setPatients([]);setPatient('');setReceipt(null);
    api<Patient[]>(`/patients?hospital=${hospital}`).then(p=>{if(alive){setPatients(p);setPatient(p[0]?.patient_id??'');}}).catch(e=>{if(alive)setError(e.message);});
    return()=>{alive=false;};
  },[hospital,hospitals.reduce((n,h)=>n+h.records,0)]);
  useEffect(()=>{
    let alive=true;setReceipt(previous=>previous?.record.patient_id===patient?previous:null);
    if(patient)api<Receipt>(`/patients/${patient}/receipt`).then(r=>{if(alive)setReceipt(r);}).catch(e=>{if(alive)setError(e.message);});
    return()=>{alive=false;};
  },[patient,runs]);
  async function action(fn:()=>Promise<void>) {
    setPending(true);setError('');setMessage('');
    try{await fn();await refresh();}catch(e){setError((e as Error).message);}finally{setPending(false);}
  }
  const run=runs.find(r=>r.id===selected)??runs.find(r=>r.evaluation&&r.status==='succeeded')??runs[0];
  const final=run?.rounds.at(-1);
  const rows=run?Object.entries(run.baselines).flatMap(([h,b])=>b.metrics?[{name:`Hospital ${h} · local`,metrics:b.metrics}]:[]):[];
  if(final?.metrics)rows.push({name:'Federated model',metrics:final.metrics});
  const comparable=(r:Run)=>run&&r.status==='succeeded'&&r.evaluation===run.evaluation&&['rounds','epochs','delta','seed','batch_size','learning_rate','clipping'].every(k=>r.config[k as keyof Run['config']]===run.config[k as keyof Run['config']])&&JSON.stringify(r.rounds.map(x=>Object.values(x.hospitals).map(h=>h.eligible_ids)))===JSON.stringify(run.rounds.map(x=>Object.values(x.hospitals).map(h=>h.eligible_ids)));
  const comparisons=runs.filter(comparable);
  const points=comparisons.filter(r=>r.config.noise>0&&r.rounds.at(-1)?.epsilon_max!=null&&r.rounds.at(-1)?.metrics?.auroc!=null);
  const maxEpsilon=Math.max(1,...points.map(r=>r.rounds.at(-1)!.epsilon_max!));
  const active=runs.find(r=>['running','queued'].includes(r.status));
  return <div className={`app view-${view}`}><a className="skip" href="#workspace">Skip to workspace</a>
    <aside className="sidebar">
      <a className="brand" href="#workspace"><img className="brand-mark" src={brandIcon} aria-hidden="true" alt="" /><span>FedConsent<small>HEALTH RESEARCH</small></span></a>
      <nav aria-label="Workspace views">{[['research',researchIcon,'Research overview'],['privacy',privacyIcon,'Privacy evidence'],['patient',patientIcon,'Patient portal']].map(([id,icon,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}><img src={icon} alt="" aria-hidden="true" /><span>{label}</span></button>)}</nav><div className="sidebar-note"><span className="status-dot"/>Consent-aware research<p>Three hospital cohorts.<br/>One inspectable experiment.</p></div>
    </aside>

    <main id="workspace"><header className="topbar"><span className="workspace-label">Pneumonia research workspace</span><span className="prototype-label">Public-data prototype</span>
      <a className="brand mobile-brand" href="#workspace"><img className="brand-mark" src={brandIcon} aria-hidden="true" alt="" /><span>FedConsent<small>HEALTH RESEARCH</small></span></a>
    </header>
    <nav className="pill-nav" aria-label="Mobile workspace views">{[['research',researchIcon,'Research overview'],['privacy',privacyIcon,'Privacy evidence'],['patient',patientIcon,'Patient portal']].map(([id,icon,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)} title={label}><img src={icon} alt="" aria-hidden="true" />{view===id && <span>{label}</span>}</button>)}</nav>
    <div className="content"><div className="page-heading"><div><h1>{view==='patient'?'Patient consent':view==='privacy'?'Privacy evidence':'Research overview'}</h1><p>{view==='patient'?'Control future research eligibility. See what changed and when.':view==='privacy'?'Inspect the privacy budget, utility tradeoff, and measured attack.':'Compare hospital models. Train together. Keep consent in the loop.'}</p></div><div className="freshness"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{marginRight:4, verticalAlign:'-2px'}}><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>{connectionError?'Offline / stale':loaded?`Updated ${updated}`:'Connecting…'}<br/><span className="muted">Local workstation</span></div></div>
    {connectionError&&<div className="notice error" role="alert">{connectionError} <button onClick={()=>void action(async()=>{})}>Retry connection</button></div>}
    {error&&<div className="notice error" role="alert">{error} <button onClick={()=>setError('')}>Dismiss</button></div>}
    <div role="status" aria-live="polite">{pending?<p className="notice">Working… Please wait.</p>:message?<p className="notice success">{message}</p>:null}</div>
    {!loaded&&!connectionError&&<p className="notice">Loading saved experiments and consent…</p>}
    {view!=='patient'&&<>
      {view==='research'&&<><section aria-labelledby="hospitals-title"><div className="section-heading"><div className="heading-with-icon"><div className="heading-icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 21h18"/><path d="M6 21V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v17"/><path d="M14 13h4a1 1 0 0 1 1 1v7"/><path d="M10 8v4"/><path d="M8 10h4"/></svg></div><div><h2 id="hospitals-title">Hospital network</h2><p>Disjoint training cohorts · model updates exchanged through Flower</p></div></div><button className="secondary" disabled={pending||health.busy||!!connectionError} onClick={()=>void action(async()=>{await api('/initialize',{});setMessage('Dataset ready. Existing consent choices were preserved.');})}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{marginRight:6}}><path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"/><path d="M16 21v-5h5"/></svg>{health.initialized?'Reload dataset':'Initialize dataset'}</button></div><div className="hospitals">{hospitals.map(h=><article className={`hospital hospital-${h.id}`} key={h.id}><div className="hospital-top"><div style={{display:'flex', alignItems:'center', gap:'8px'}}><span className="hospital-icon" aria-hidden="true"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 21h18"/><path d="M6 21V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v17"/><path d="M14 13h4a1 1 0 0 1 1 1v7"/><path d="M10 8v4"/><path d="M8 10h4"/></svg></span><h3 style={{margin:0}}>Hospital {h.id}</h3></div><span className="badge"><span className="status-dot" style={{background: h.status.startsWith('ready') ? '#10b981' : '#ccc'}}></span>{h.status.startsWith('ready')?'Ready':'Load Data'}</span></div><p className="count">{h.eligible}<small> / {h.records} eligible</small></p><div className="distribution" aria-hidden="true"><span style={{width:`${h.distribution&&h.records?h.distribution.normal/h.records*100:0}%`}}/></div><p className="legend">Normal <strong>{h.distribution?.normal??'—'}</strong><span>Pneumonia <strong>{h.distribution?.pneumonia??'—'}</strong></span></p><footer><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{marginRight:6, verticalAlign:'-2px'}}><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>{h.records-h.eligible} excluded by consent</footer><button className="hospital-action" onClick={()=>{setHospital(h.id);setView('patient');}}>Review consent <span aria-hidden="true">↗</span></button></article>)}</div><p className="caption">Logical boundaries in one trusted process. This demo does not physically isolate hospital data.</p></section>
      <section className="panel training"><div className="heading-with-icon"><div className="heading-icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4.5 3h15"/><path d="M10 3v5.39l-4.6 11.12A2 2 0 0 0 7.24 22h9.52a2 2 0 0 0 1.84-2.49L14 8.39V3"/><path d="M7 16h10"/></svg></div><div><h2>Experiment control</h2><p>Eligibility is captured before each round. Two local epochs per round · seed 42</p></div></div><form onSubmit={e=>{e.preventDefault();void action(async()=>{const r=await api<{id:string}>('/experiments',{noise,rounds,epochs:2});setSelected(r.id);setMessage(`Training queued: ${r.id.slice(0,8)}. Consent changes remain available.`);});}}><label>Privacy configuration<select value={noise} onChange={e=>setNoise(Number(e.target.value))}><option value={0}>No DP · local + federated</option><option value={.8}>DP · noise 0.8</option><option value={1.2}>DP · noise 1.2</option><option value={2}>DP · noise 2.0</option></select></label><label>Rounds<input type="number" min={1} max={10} required value={rounds} onChange={e=>setRounds(Number(e.target.value))}/></label><button className="primary" disabled={pending||health.busy||!health.initialized||!!connectionError}>Start training <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{marginLeft:6}}><path d="M5 12h14"/><path d="M12 5l7 7-7 7"/></svg></button></form><div className="job-status-box" role="status"><span className="status-dot" style={{background: health.initialized&&!health.busy ? '#10b981' : '#ccc'}}></span><div><strong>{health.busy?active?`Training ${active.rounds.length}/${active.config.rounds} rounds · ${active.id.slice(0,8)}`:'Loading data…':health.initialized?'Ready to train':'Initialize dataset'}</strong><p>{health.busy?'Processing rounds in background':'Configure settings and start training'}</p></div></div></section></>}
      <section className="panel evidence"><div className="section-heading"><div className="heading-with-icon"><div className="heading-icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 7V4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3"/><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M12 11v4"/></svg></div><div><h2>{view==='privacy'?'Privacy & utility':'Saved experiments'}</h2><p>{view==='privacy'?'Inspect the DP accountant.':'Compare results from completed training runs.'}</p></div></div>{run&&<a className="button secondary" href={`/api/experiments/${run.id}/download`} download>Export evidence <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{marginLeft:6}}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg></a>}</div>
      {!runs.length?<div className="empty"><h3>No measured results yet</h3><p>Initialize the dataset, then run a non-DP experiment to compare local and federated models.</p></div>:<><div style={{display:'flex', gap:'20px', alignItems:'center', flexWrap:'wrap'}}><label className="run-selector" style={{flex:1, maxWidth:'500px'}}>Experiment<select value={run?.id} onChange={e=>setSelected(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{runLabel(r)}{!r.evaluation?' · legacy':''}</option>)}</select></label>{run&&<div className="run-meta" style={{marginTop:'20px'}}><span className={`run-status status-${run.status}`}>{run.status}</span><span>{date(run.started_at)}</span><code>{run.id.slice(0,8)}</code><span>{run.rounds.length}/{run.config.rounds} rounds saved</span></div>}</div>{run&&<>{run.error&&<p className="notice error" role="alert">{run.error} Previous completed rounds remain below; this is not a successful final result.</p>}{!run.evaluation&&run.rounds.length>0&&<p className="notice">Legacy experiment: fixed threshold 0.5. Use a new run for calibrated results.</p>}
      {view==='research'?<><div className="metric-strip"><div><div className="metric-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="18" y="3" width="4" height="18"/><rect x="10" y="8" width="4" height="13"/><rect x="2" y="13" width="4" height="8"/></svg></div><div className="metric-content"><span>Federated AUROC</span><strong>{value(final?.metrics?.auroc)}</strong><small>Ranking discrimination · higher is better</small></div></div><div><div className="metric-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg></div><div className="metric-content"><span>Federated accuracy</span><strong>{percent(final?.metrics?.accuracy)}</strong><small>{final?.metrics?.test_count??'—'} official test records</small></div></div><div><div className="metric-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M12 8v4"/><path d="M12 16h.01"/></svg></div><div className="metric-content"><span>Privacy budget ε</span><strong>{run.config.noise?value(final?.epsilon_max):'No DP'}</strong><small>{run.config.noise?`Maximum hospital ε · δ ${run.config.delta}`:'Unprotected training baseline'}</small></div></div></div>
      {rows.length>0?<><div className="model-comparison-header"><div className="heading-with-icon"><div className="heading-icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="18" y="3" width="4" height="18"/><rect x="10" y="8" width="4" height="13"/><rect x="2" y="13" width="4" height="8"/></svg></div><div><h2>Model comparison</h2><p>Same official test split · thresholds selected on validation for calibrated runs.</p></div></div><p className="caption" style={{display:'flex', alignItems:'center', gap:'8px', maxWidth:'400px', margin:0}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{flexShrink:0}}><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg> Federation may help some hospitals without beating the strongest local model. Compare all metrics; higher accuracy alone can hide label imbalance.</p></div><div className="metric-tabs" role="group" aria-label="Comparison metric">{(['auroc','accuracy','f1'] as const).map(m=><button key={m} aria-pressed={metric===m} onClick={()=>setMetric(m)}>{m==='accuracy'?'Accuracy':m.toUpperCase()}</button>)}</div><div className="new-comparison-container" aria-label={`${metric} comparison`}><div className="comparison-visuals"><div className="federated-widget"><img className="research-sculpture" src={sculpture} alt="" aria-hidden="true" width="280" height="280"/><div className="federated-content" aria-live="polite"><span>Federated {metric==='accuracy'?'accuracy':metric.toUpperCase()}</span><strong>{metric==='accuracy'?percent(final?.metrics?.[metric]):value(final?.metrics?.[metric])}</strong></div></div><div className="hospital-pills">{rows.filter(r=>r.name!=='Federated model').map(r=><div className="hospital-pill" key={r.name}><div className="pill-fill" style={{width:`${(r.metrics[metric]??0)*100}%`}}/><div className="pill-content"><div className="pill-info"><div className="pill-name">{r.name.split(' · ')[0]}<span>Local model</span></div><div className="pill-score">{metric==='accuracy'?percent(r.metrics[metric]):value(r.metrics[metric])}</div></div></div></div>)}</div></div><div className="comparison-table-wrapper"><MetricTable rows={rows}/></div></div></>:<p className="empty">Training results will appear after the first model finishes.</p>}
      {run.rounds.length>0&&<details><summary>Round-by-round metrics and consent snapshots</summary><MetricTable rows={run.rounds.flatMap(r=>r.metrics?[{name:`Round ${r.round}`,metrics:r.metrics}]:[])}/><div className="table-scroll"><table><thead><tr><th>Round</th><th>Snapshot</th><th>Hospital A</th><th>Hospital B</th><th>Hospital C</th></tr></thead><tbody>{run.rounds.map(r=><tr key={r.round}><th>{r.round}</th><td>{date(r.snapshot_at)}</td>{['A','B','C'].map(h=><td key={h}>{r.hospitals[h]?.count??'—'} eligible</td>)}</tr>)}</tbody></table></div></details>}</>:<>
      <div className="notice">{run.config.noise?`This run: noise ${run.config.noise}, clipping ${run.config.clipping}, δ ${run.config.delta}. Lower epsilon indicates a stronger bound under this mechanism’s assumptions.`:'This selected run has no differential privacy guarantee. Select a DP run to inspect its accountant.'}</div><p>DP limits how much a training record can affect the model. It does not hide consent status, remove past influence, or make a model medically safe.</p><div className="privacy-grid tradeoff"><div className="privacy-chart"><h3>Measured privacy–utility tradeoff</h3><p className="caption">Only successful runs with identical cohorts, epochs, rounds, seed, clipping and evaluation method are shown.</p>{points.length?<svg viewBox="0 0 480 270" role="img" aria-label="Epsilon versus AUROC. Exact values in the table below."><line x1="55" y1="220" x2="450" y2="220"/><line x1="55" y1="25" x2="55" y2="220"/>{[0,.5,1].map(v=><g key={v}><line className="grid-line" x1="55" x2="450" y1={220-v*190} y2={220-v*190}/><text x="20" y={225-v*190}>{v}</text></g>)}<text x="14" y="16">AUROC</text><text x="140" y="260">ε · lower is more private</text><text x="50" y="240">0</text><text x="420" y="240">{maxEpsilon.toFixed(1)}</text>{points.map(r=><g key={r.id}><circle cx={55+r.rounds.at(-1)!.epsilon_max!/maxEpsilon*380} cy={220-r.rounds.at(-1)!.metrics!.auroc!*190} r="7"><title>{runLabel(r)}: ε {value(r.rounds.at(-1)!.epsilon_max)}, AUROC {value(r.rounds.at(-1)!.metrics?.auroc)}</title></circle></g>)}</svg>:<p className="empty">No comparable DP measurements yet. Run DP with the same cohort and settings.</p>}</div><div><h3>Comparable experiments</h3><div className="table-scroll"><table><thead><tr><th>Run / noise</th><th>ε max</th><th>AUROC</th></tr></thead><tbody>{comparisons.map(r=><tr key={r.id}><th><button className="link" onClick={()=>setSelected(r.id)}>{r.id.slice(0,8)}</button><small>{r.config.noise||'No DP'}</small></th><td>{r.config.noise?value(r.rounds.at(-1)!.epsilon_max):'No DP'}</td><td>{value(r.rounds.at(-1)!.metrics?.auroc)}</td></tr>)}</tbody></table></div></div></div>
      <h3>Membership-inference measurement</h3>{run.attack?.status==='measured'?<><p>Can a loss-based attacker distinguish training-cohort members from unused records?</p><div className="metric-strip"><div><span>Attack AUROC</span><strong>{value(run.attack.auroc)}</strong><small>0.5 is chance-level discrimination</small></div><div><span>Balanced accuracy</span><strong>{percent(run.attack.balanced_accuracy)}</strong><small>Threshold calibrated on separate records</small></div><div><span>Held-out attack records</span><strong>{(run.attack.counts?.evaluation_members??0)+(run.attack.counts?.evaluation_nonmembers??0)}</strong><small>Matched member / nonmember class mix</small></div></div><p className="caption">TPR {percent(run.attack.tpr)} · FPR {percent(run.attack.fpr)}. {run.attack.limitation}</p><details><summary>Attack protocol and sample counts</summary><p>{run.attack.scope}</p><pre>{JSON.stringify(run.attack.counts,null,2)}</pre></details></>:<p className="empty">{run.attack?.reason??(run.status==='succeeded'?'Not measured for this historical run. Start a new experiment to measure the attack.':'Attack measurement follows training.')}</p>}
      <details><summary>Accountant evidence by round and hospital</summary><pre>{JSON.stringify(run.rounds.map(r=>({round:r.round,hospitals:Object.fromEntries(Object.entries(r.hospitals).map(([h,v])=>[h,{count:v.count,privacy:v.privacy??'No DP'}]))})),null,2)}</pre></details><p className="caption">{run.privacy_scope} Secure RNG is disabled. Attack statistics and public evaluation data are outside the training DP mechanism.</p></>}
      </>}</>}
      </section>
    </>}
    {view==='patient'&&<><p className="notice">Demo role switch, not authentication. These IDs represent public dataset images, not verified patients.</p><section className="panel"><div className="section-heading"><div><h2>Your research choice</h2></div>{receipt&&<a className="button secondary" href={`/api/patients/${patient}/receipt?download=true`} download>Download receipt ↓</a>}</div><div className="patient-select"><label>Hospital<select disabled={pending} value={hospital} onChange={e=>setHospital(e.target.value)}>{['A','B','C'].map(h=><option key={h}>{h}</option>)}</select></label><label>Simulated record<select disabled={pending||!patients.length} value={patient} onChange={e=>setPatient(e.target.value)}>{patients.map(p=><option key={p.patient_id}>{p.patient_id}</option>)}</select></label></div>{!patient?<p className="empty">Initialize the dataset in Research overview to see records.</p>:!receipt?<p className="empty">Loading your receipt…</p>:<><div className={`consent-banner ${receipt.eligible_now?'allowed':'withdrawn'}`}><div><span className="badge">{receipt.record.status.toUpperCase()}</span><h3>{receipt.eligible_now?'Eligible for future rounds':'Excluded from future rounds'}</h3><p>{receipt.eligible_now?'Your record can enter the next training snapshot.':'Your record will not enter the next training snapshot.'}</p></div><button className={receipt.record.status==='active'?'danger':'primary'} disabled={pending||!!connectionError} onClick={()=>void action(async()=>{await api(`/patients/${patient}/consent`,{status:receipt.record.status==='active'?'withdrawn':'active'});setReceipt(await api(`/patients/${patient}/receipt`));setMessage('Consent saved and audited. The next round uses your updated choice.');})}>{receipt.record.status==='active'?'Withdraw consent':'Grant consent'}</button></div><dl className="scope"><div><dt>Project</dt><dd>{receipt.record.project}</dd></div><div><dt>Purpose</dt><dd>{receipt.record.purpose}</dd></div><div><dt>Policy version</dt><dd>{receipt.record.policy}</dd></div></dl><div className="notice"><strong>What withdrawal means</strong><p>{receipt.withdrawal_explanation} A round already started may still use its earlier snapshot.</p></div><p className="caption">Initial consent was simulated. {receipt.raw_data}</p>
      <div className="privacy-grid"><section><h3>Consent history</h3>{receipt.history.length?<ol className="timeline">{receipt.history.map(a=><li key={a.id}><strong>{a.action==='active'?'Consent granted':'Consent withdrawn'}</strong><time>{date(a.at)}</time></li>)}</ol>:<p className="empty">No changes yet. Initial active consent was simulated.</p>}</section><section><h3>Round eligibility receipt</h3><p className="caption">Eligibility is not proof of individual Poisson sampling or contribution to accuracy.</p>{receipt.rounds.length?<div className="receipt-list">{receipt.rounds.map(r=><article key={`${r.run_id}-${r.round}`}><span className={`badge ${r.eligible?'':'bad'}`}>{r.eligible?'ELIGIBLE':'EXCLUDED'}</span><strong>Round {r.round} · {r.run_id.slice(0,8)}</strong><p>{r.participation}</p><small>{date(r.snapshot_at)}</small></article>)}</div>:<p className="empty">No saved round snapshots yet.</p>}</section></div></>}
    </section></>}
    <footer className="page-footer"><strong>FedConsent Health</strong><span>Consent enforcement + inspectable research evidence</span><p>Local public-data prototype. No authentication, secure aggregation, clinical validation or combined privacy guarantee across runs.</p></footer>
    </div></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
